package com.example.design.launcher.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.design.launcher.dao.AppInfo;
import com.example.design.launcher.dao.HomeAppInfo;

import com.example.design.launcher.dao.AppInfoDao;
import com.example.design.launcher.dao.HomeAppInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig appInfoDaoConfig;
    private final DaoConfig homeAppInfoDaoConfig;

    private final AppInfoDao appInfoDao;
    private final HomeAppInfoDao homeAppInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        appInfoDaoConfig = daoConfigMap.get(AppInfoDao.class).clone();
        appInfoDaoConfig.initIdentityScope(type);

        homeAppInfoDaoConfig = daoConfigMap.get(HomeAppInfoDao.class).clone();
        homeAppInfoDaoConfig.initIdentityScope(type);

        appInfoDao = new AppInfoDao(appInfoDaoConfig, this);
        homeAppInfoDao = new HomeAppInfoDao(homeAppInfoDaoConfig, this);

        registerDao(AppInfo.class, appInfoDao);
        registerDao(HomeAppInfo.class, homeAppInfoDao);
    }
    
    public void clear() {
        appInfoDaoConfig.clearIdentityScope();
        homeAppInfoDaoConfig.clearIdentityScope();
    }

    public AppInfoDao getAppInfoDao() {
        return appInfoDao;
    }

    public HomeAppInfoDao getHomeAppInfoDao() {
        return homeAppInfoDao;
    }

}
