package com.example.design.designCombat.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.design.designCombat.dao.OrderInfo;

import com.example.design.designCombat.dao.OrderInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig orderInfoDaoConfig;

    private final OrderInfoDao orderInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        orderInfoDaoConfig = daoConfigMap.get(OrderInfoDao.class).clone();
        orderInfoDaoConfig.initIdentityScope(type);

        orderInfoDao = new OrderInfoDao(orderInfoDaoConfig, this);

        registerDao(OrderInfo.class, orderInfoDao);
    }
    
    public void clear() {
        orderInfoDaoConfig.clearIdentityScope();
    }

    public OrderInfoDao getOrderInfoDao() {
        return orderInfoDao;
    }

}
